In [1]:
import pandas as pd

In [37]:
data = [[1, 2, '2016-03-01', 5], [1, 2, '2016-05-02', 6], [2, 3, '2017-06-25', 1], [3, 1, '2016-03-02', 0], [3, 4, '2018-07-03', 5]]
activity = pd.DataFrame(data, columns=['player_id', 'device_id', 'event_date', 'games_played']).astype({'player_id':'Int64', 'device_id':'Int64', 'event_date':'datetime64[ns]', 'games_played':'Int64'})

In [38]:
activity

   player_id  device_id event_date  games_played
0          1          2 2016-03-01             5
1          1          2 2016-05-02             6
2          2          3 2017-06-25             1
3          3          1 2016-03-02             0
4          3          4 2018-07-03             5

In [39]:
activity.event_date = activity.event_date.sort_values()
activity

   player_id  device_id event_date  games_played
0          1          2 2016-03-01             5
1          1          2 2016-05-02             6
2          2          3 2017-06-25             1
3          3          1 2016-03-02             0
4          3          4 2018-07-03             5

In [40]:
activity = activity.sort_values(by=['player_id', 'event_date'])
activity

   player_id  device_id event_date  games_played
0          1          2 2016-03-01             5
1          1          2 2016-05-02             6
2          2          3 2017-06-25             1
3          3          1 2016-03-02             0
4          3          4 2018-07-03             5

In [46]:
result = activity.groupby('player_id')

In [47]:
result = result['event_date'].min().reset_index()

In [48]:
result

   player_id event_date
0          1 2016-03-01
1          2 2017-06-25
2          3 2016-03-02

In [35]:
result.rename(columns={"event_date":"first_login"}, inplace=True)

In [36]:
result

   player_id first_login
0          1  2016-03-01
1          2  2017-06-25
2          3  2016-03-02