In [1]:
import pandas as pd

In [2]:
data = [[3, 'Brad', None, 4000], [1, 'John', 3, 1000], [2, 'Dan', 3, 2000], [4, 'Thomas', 3, 4000]]
employee = pd.DataFrame(data, columns=['empId', 'name', 'supervisor', 'salary']).astype({'empId':'Int64', 'name':'object', 'supervisor':'Int64', 'salary':'Int64'})
data = [[2, 500], [4, 2000]]
bonus = pd.DataFrame(data, columns=['empId', 'bonus']).astype({'empId':'Int64', 'bonus':'Int64'})

In [3]:
employee

   empId    name  supervisor  salary
0      3    Brad        <NA>    4000
1      1    John           3    1000
2      2     Dan           3    2000
3      4  Thomas           3    4000

In [4]:
bonus

   empId  bonus
0      2    500
1      4   2000

In [7]:
result = employee.merge(bonus, how='left', on='empId')
result

   empId    name  supervisor  salary  bonus
0      3    Brad        <NA>    4000   <NA>
1      1    John           3    1000   <NA>
2      2     Dan           3    2000    500
3      4  Thomas           3    4000   2000

In [15]:
result = result[(result["bonus"] < 1000) | (result["bonus"].isna())]
result

   empId  name  supervisor  salary  bonus
0      3  Brad        <NA>    4000   <NA>
1      1  John           3    1000   <NA>
2      2   Dan           3    2000    500

In [17]:
result[["name","bonus"]]

   name  bonus
0  Brad   <NA>
1  John   <NA>
2   Dan    500