In [1]:
import pandas as pd

In [ ]:
data = [[1, 'Joe', 70000, 3], [2, 'Henry', 80000, 4], [3, 'Sam', 60000, None], [4, 'Max', 90000, None]]
employee = pd.DataFrame(data, columns=['id', 'name', 'salary', 'managerId']).astype({'id':'Int64', 'name':'object', 'salary':'Int64', 'managerId':'Int64'})

employee

   id   name  salary  managerId
0   1    Joe   70000          3
1   2  Henry   80000          4
2   3    Sam   60000       <NA>
3   4    Max   90000       <NA>

In [ ]:
employee_managers = employee.merge(employee,how="inner", left_on="managerId", right_on="id")
salary = employee_managers[["name_x","salary_x","salary_y"]]

salary

  name_x  salary_x  salary_y
0    Joe     70000     60000
1  Henry     80000     90000

In [13]:
result = salary[salary["salary_x"] > salary["salary_y"]]
result

  name_x  salary_x  salary_y
0    Joe     70000     60000

In [14]:
result = result.rename(columns={"name_x" : "Employee"}).drop("salary_y",axis=1).drop("salary_x",axis=1)
result

  Employee
0      Joe